[package]
name = "ethereum-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = { path = "../types" }
rocksdb = "0.21"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.8"
