[package]
name = "ethereum-network"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = { path = "../types" }
ethereum-rlp = { path = "../rlp" }
tokio = { version = "1.35", features = ["full"] }
thiserror = "1.0"
